version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - mongo-env-url
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: